name: 'My first github action'

on: push

jobs:
	first-job:
	name: 'first job'

	runs-on: ubuntu-latest

	steps:
	- name: Say Hello World 1
	shell : bash
	env:
		STEP_LEVEL_1: 'THIS COM STEP LEVEL 1'
	run: |
		echo "Hello World from step 1"
		echo "STEP_VALUE_1='THIS IS SET BY STEP !'" >> $GITHUB_ENV

	- name: Say Hello World 2
	shell: pwsh
	run: |
		echo "Hello World from step 2"
		echo "VALUE:$env:STEP_VALUE_1"
    echo "VALUE: ${{ env.STEP_VALUE_1 }}"