# name : github workflow를 가리키는 고유 이름
# on : github action의 실행 타이밍
# file하나당 event 하나가 좋음.
name: 'My first github action'

on: push

# 어디에서든 참조 가능
env:
	WORKFLOW_LEVEL: 'THIS VALUE COMES FROM THE WORKFLOW LEVEL'

jobs:
	#  해당 job의 빌드 서버
	first-job:
	name: 'first job'

    # 운영체제 (macos-latest, ubuntu-latest)
	runs-on: ubuntu-latest

	# 아래 step들에서는 전부 사용 가능
	env:
	JOB_LEVEL_1: 'THIS COMES FROM JOB LEVEL 1'

    # 돌리는 순서
	steps:
	- name: Say Hello World 1
	shell : bash
	env:
		STEP_LEVEL_1: 'THIS COM STEP LEVEL 1'
	run: |
		echo "Hello World from step 1"
		echo $WORKFLOW_LEVEL
		echo $JOB_LEVEL_1
		echo $JOB_LEVEL_2
		echo $STEP_LEVEL_1

	- name: Say Hello World 2
	shell: pwsh
	run: |
		echo "Hello World from step 1"
		echo $WORKFLOW_LEVEL
		echo $JOB_LEVEL_1
		echo $JOB_LEVEL_2
		echo $STEP_LEVEL_1

	second-job:
	name: 'second job'

    # 운영체제 (macos-latest, ubuntu-latest)
	runs-on: ubuntu-latest

	# 아래 step들에서는 전부 사용 가능
	env:
	JOB_LEVEL_1: 'THIS COMES FROM JOB LEVEL 1'

    # 돌리는 순서
	steps:
	- name: Say Hello World 1
	shell : bash
	env:
		STEP_LEVEL_1: 'THIS COM STEP LEVEL 1'
	run: |
		echo "Hello World from step 1"
		echo $WORKFLOW_LEVEL
		echo $JOB_LEVEL_1
		echo $JOB_LEVEL_2
		echo $STEP_LEVEL_1
		echo $STEP_LEVEL_2

	- name: Say Hello World 2
	shell: pwsh
	env:
		STEP_LEVEL_1: 'THIS COM STEP LEVEL 2'
	run: |
		echo "Hello World from step 1"
		echo $WORKFLOW_LEVEL
		echo $JOB_LEVEL_1
		echo $JOB_LEVEL_2
		echo $STEP_LEVEL_1
		echo $STEP_LEVEL_2