name: 'My first github action'

on: push

jobs:
  first-job:
    name: 'first job'

    strategy:
      matrix:
        os: [ 'windows-latest', 'macos-latest', 'ubuntu-latest' ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: mask value
      id: first
      shell: bash
      run: |
        echo "OS: ${{ matrix.os }}"
