# name : github workflow를 가리키는 고유 이름
# on : github action의 실행 타이밍
# file하나당 event 하나가 좋음.
name: 'My first github action'

on: push

jobs:
	#  해당 job의 빌드 서버
	first-job:
	name: 'first job'

    # 운영체제 (macos-latest, ubuntu-latest)
	runs-on: ubuntu-latest

    # 돌리는 순서
	steps:
	- name: Say Hello World 1
	shell : bash
	env:
		STEP_LEVEL_1: 'THIS COM STEP LEVEL 1'
	run: |
		echo "Hello World from step 1"
		# echo한 값을 GITHUB_ENV에 append (>>)
		echo "STEP_VALUE_1='THIS IS SET BY STEP !'" >> $GITHUB_ENV

	- name: Say Hello World 2
	shell: pwsh
	run: |
		echo "Hello World from step 2"
		echo "VALUE:$env:STEP_VALUE_1"
    echo "VALUE: ${{env.STEP_VALUE_1 }}"